### ISSUE TITLE
[Feature - 1.10.2] - Ender IO +Botania singularities

### ISSUE THREAD

**Issue by Protheus** [TheLMiffy1111/JAOPCASingularities#2]
Request for additional singularities:
**Botania:**
- Terrasteel block
- Manasteel block
- Elementium block
- Mana Diamond block
- Dragon Stone block

**EnderIO:**
- Electric steel block
- Energetic alloy block
- Vibrant alloy block
- Redstone alloy block
- Conductive iron block
- Pulsating iron block
- Darksteel block
- Soularium Block

**Comment by TheLMiffy1111** [comment]
Thanks for your request, but I will not be adding those singularities to this mod, as this mod is based on JAOPCA, and will only add singularities for the ores that JAOPCA detects.

**Comment by TheLMiffy1111** [comment]
Already "added"
